version: '3'

# ============== Variables ==============
vars:
  # Short git commit hash
  COMMIT_HASH:
    sh: git rev-parse --short HEAD
  # Latest tag version
  VERSION:
    sh: git describe --tags --abbrev=0
  # Go build flags with embedded version info
  GO_FLAGS: "-s -w -X main.CommitHash={{.COMMIT_HASH}} -X main.Version={{.VERSION}}"

  DEV_RUN_FLAGS: ""

# ============== Tasks ==============
tasks:

  # Clean Go environment
  clean:
    desc: "Clean Go modules and build artifacts"
    silent: true
    cmds:
      - echo "=== Cleaning Go Environment ==="
      - go mod tidy
      - go clean
      - echo "=== Clean Completed ==="

  # Build binary
  build:
    desc: "Build binary"
    silent: true
    cmds:
      - echo "=== Building Binary ==="
      - |
        go build -trimpath -ldflags="{{.GO_FLAGS}}" \
        -o "./ipcsv2base.exe" \
        -v "./cmd/ipcsv2base/main.go"
      - echo "=== Build Completed ==="